# phrase_library.py

PHRASES = [

    # --- UNIVERSAL MOMENTUM PHRASES ---
    "momentum shift",
    "has all the momentum",
    "storming through",
    "pulling away",
    "the tide has turned",
    "on the back foot",
    "game on now",
    "has gone flat",
    "completely dominant",
    "rattled",
    "no resistance",
    "hanging on",
    "looks exhausted",
    "responds with fire",
    "he’s folding",
    "they’re crumbling",
    "mental edge",
    "unanswered points",
    "composure breaking down",
    "about to crack",
    "losing control",
    "emphatic push",

    # --- TENNIS ---
    "broken serve",
    "on the ropes",
    "dictating play",
    "clean winner",
    "flattened out",
    "gets the break",
    "can't hold serve",
    "pushing baseline",
    "struggling to stay in rallies",
    "won't last long",
    "aggressive return",
    "takes the set",
    "no answers",
    "overwhelmed on second serve",
    "long rally loss",
    "takes control of the court",

    # --- SOCCER / FOOTBALL ---
    "relentless pressure",
    "wave after wave",
    "under siege",
    "leaking at the back",
    "can't clear",
    "all one way",
    "desperate defending",
    "clinical in front of goal",
    "bodies on the line",
    "brilliant finish",
    "against the run of play",
    "dominant spell",
    "losing midfield battle",
    "goal incoming",
    "soaking up pressure",
    "in complete control",

    # --- RUGBY LEAGUE / NRL ---
    "on the front foot",
    "dominant set",
    "soft underbelly",
    "leaking metres",
    "linebreak factory",
    "carving through",
    "exposing the edge",
    "defensive cracks showing",
    "kick pressure building",
    "hammering that right edge",
    "can't hold them out",
    "repeat set pressure",
    "suffocating them in their own half",
    "no go forward",
    "slow off the line",
    "fatigue kicking in",

    # --- BASKETBALL ---
    "huge run",
    "outscored 10-0",
    "offensive blitz",
    "draining threes",
    "can’t get a stop",
    "no defensive presence",
    "fast break after fast break",
    "momentum has swung",
    "losing the boards",
    "turnover after turnover",
    "they’ve gone cold",
    "locked in defensively",
    "on fire from deep",

    # --- COMPOSURE & PSYCHOLOGICAL PRESSURE ---
    "lost his head",
    "boiling over",
    "clearly frustrated",
    "rattled mentally",
    "backpedaling under pressure",
    "no leadership out there",
    "sinking feeling",
    "panic mode",
    "can't stay composed",
]